AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: |
  Lambda functions that monitor running EC2 instances.
  If the instance has "TTL" key, it is interpreted as expected time that the instance will live (in hours).
  If the expected running time is exceeded, a notification is sent.

Globals:
  Function:
    Timeout: 3

Parameters:
  TopicName:
    Type: String
    Description: Github issued OAuth client ID


Resources:
  # Define the SNS topic
  MySnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: 'ExampleTopic'

  TopicPublisherFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.handler
      Runtime: nodejs18.x
      MemorySize: 128
      Environment:
        Variables:
          SNStopic: !Ref MySnsTopic
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt MySnsTopic.TopicName
        - EC2DescribePolicy: {}

  ScheduledEventLogger:
    Type: AWS::Serverless::Function
    Properties:
      Description: A Lambda function that logs the payload of messages sent to an associated SQS queue.
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      CodeUri: src/
      Handler: app.scheduledEventLoggerHandler
      Environment:
        Variables:
          SNStopic: !Ref MySnsTopic
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt MySnsTopic.TopicName
        - EC2DescribePolicy: {}
      Events:
        CloudWatchEvent:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)

Outputs:
  TopicPublisherFunction:
    Description: TopicPublisherFunction function name
    Value: !Ref TopicPublisherFunction

  SNStopicName:
    Description: SNS topic name
    Value: !GetAtt MySnsTopic.TopicName

  SNStopicARN:
    Description: SNS topic ARN
    Value: !Ref MySnsTopic
